import type { Metadata } from "next";
import localFont from "next/font/local";




export const metadata: Metadata = {
  title: "Welcometo Beauty Butler for Customers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`$ antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
